language: python
python:
  - "3.5"

branches:
  only:
    - master

before_script:
  - psql -c 'create database puckdb_test;' -U postgres

addons:
  postgresql: '9.5'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - deps='pip numpy pandas requests nose sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - travis_retry pip install coveralls
  - travis_retry pip install -r requirements.txt

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv

script: nosetests --with-coverage

after_success:
  - coveralls
