language: python
python:
  - "3.5"

branches:
  only:
    - master

before_script:
  - psql -c 'create database puckdb_test;' -U postgres

addons:
  postgresql: '9.4'

install:
  # Install conda
  - sudo pip install conda
  # install deps
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip numpy pandas requests nose sphinx'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - travis_retry pip install -r requirements.txt

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv

script: nosetests
