language: python
python:
  - "3.5"
  - "nightly"

branches:
  only:
    - master

install:
  - travis_retry pip install nose
  - travis_retry pip install .

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv

script: nosetests
